# Default values for italentup-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

component: stripe
partOf: ITU

replicaCount: 1

image:
  repository: okteto.dev
  tag:
    common: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
    queue:
      cpu: 250m
      memory: 512Mi
  requests:
    cpu: 25m
    memory: 128Mi

appKey: base64:G83NHliYXg5dWZuODgzMXUcnp1djNvOWVqMjZ6a2dhb=

app:
  debug: true
  name: stripe
  env: test
  log: daily
  logLevel: debug
  domain: st-stripe-app-${OKTETO_NAMESPACE}.pedagoo.tech
  url: https://st-stripe-app-${OKTETO_NAMESPACE}.pedagoo.tech
  asseturl: https://st-stripe-app-${OKTETO_NAMESPACE}.pedagoo.tech

dbStripe:
  connection: stripe_mysql
  host: 10.191.0.244
  port: 3306
  database: ${OKTETO_NAMESPACE}_stripe
  username: ptsadmin
  password: 6SyipLohQFXAJIuwjFtXszx4Vh5zaA7u
  dbSecure: false

mail:
  host: smtp.mailtrap.io
  port: 2525
  username: 64b1f28b113c89
  password: 051dc322d25c52
  driver: smtp
  encryption: tls
  fromAddress: noreply@italentup.com
  fromName: iTalentUp

driver:
  broadcast: log
  cache: file
  queue: sync

azure:
  stripe:
    storage:
      name: saitunpewus2001
      key: L6j6UaPesHqNhJigvOsa5ST9aSTpEDNlbj6WpMUQKq2+2/0FsaUzbPrf2gySmq/LgjRthGkzM13++AStNPcjHg==
      string: DefaultEndpointsProtocol=https;AccountName=saitunpewus2001;AccountKey=L6j6UaPesHqNhJigvOsa5ST9aSTpEDNlbj6WpMUQKq2+2/0FsaUzbPrf2gySmq/LgjRthGkzM13++AStNPcjHg==;EndpointSuffix=core.windows.net
      url: https://saitunpewus2001.blob.core.windows.net
      container:
        images: images
