apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stripe-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "stripe-app.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_ENV: {{ .Values.app.env | quote }}
  APP_DEBUG: {{ .Values.app.debug | quote }}
  APP_URL: {{ .Values.app.url | quote }}
  ASSET_URL: {{ .Values.app.asseturl | quote }}
  APP_LOG_CHANNEL: {{ .Values.app.log | quote }}
  APP_LOG_LEVEL: {{ .Values.app.logLevel | quote }}

  MAIL_HOST: {{ .Values.mail.host | quote }}
  MAIL_PORT: {{ .Values.mail.port | quote }}
  MAIL_MAILER: {{ .Values.mail.driver | quote }}
  MAIL_ENCRYPTION: {{ .Values.mail.encryption | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.mail.fromAddress | quote }}
  MAIL_FROM_NAME: {{ .Values.mail.fromName | quote }}

  BROADCAST_DRIVER: {{ .Values.driver.broadcast | quote }}
  CACHE_DRIVER: {{ .Values.driver.cache | quote }}
  QUEUE_CONNECTION: {{ .Values.driver.queue | quote }}

  SESSION_DOMAIN: {{ .Values.session.domain | quote }}
  SESSION_LIFETIME: {{ .Values.session.lifetime | quote }}
  SESSION_DRIVER: {{ .Values.session.driver | quote }}

  QUEUE_COMMANDS_NAME: {{ .Values.queue.name | quote }}

  REDIS_CLIENT: {{ .Values.redis.client | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}

  DELIVERY_URL: {{ .Values.serviceUrl.delivery | quote }}
  ITEMBANK_URL: {{ .Values.serviceUrl.itembank | quote }}
  SERVICE_PUBLIC_API_URL: {{ .Values.publicapi.url | quote }}
  SERVICE_PUBLIC_API_CLIENT_ID: {{ .Values.publicapi.client_id | quote }}
  SERVICE_PUBLIC_API_CLIENT_SECRET: {{ .Values.publicapi.secret_id | quote }}

  MSGRAPH_CLIENT_ID: {{ .Values.msgraph.client_id | quote }}
  MSGRAPH_OAUTH_URL: {{ .Values.msgraph.oauth_url | quote }}
  MSGRAPH_LANDING_URL: {{ .Values.msgraph.landing_url | quote }}
  MSGRAPH_PREFER_TIMEZONE: {{ .Values.msgraph.prefer_timezone | quote }}
