apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stripe-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "stripe-app.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
stringData:
  APP_KEY: {{ .Values.appKey | quote }}

  DB_CONNECTION: {{ .Values.dbStripe.connection | quote }}
  DB_HOST_STRIPE: {{ .Values.dbStripe.host | quote }}
  DB_PORT_STRIPE: {{ .Values.dbStripe.port | quote }}
  DB_DATABASE_STRIPE: {{ .Values.dbStripe.database | quote }}
  DB_USERNAME_STRIPE: {{ .Values.dbStripe.username | quote }}
  DB_PASSWORD_STRIPE: {{ .Values.dbStripe.password | quote }}
  DB_SECURE_STRIPE: {{ .Values.dbStripe.dbSecure | quote }}

  REDIS_PASSWORD: {{ .Values.redis.password | quote }}

  MAIL_USERNAME: {{ .Values.mail.username | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | quote }}

  MSGRAPH_SECRET_ID: {{ .Values.msgraph.secret_id | quote }}

type: Opaque
